Doctor/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views
from .views import DoctorViewSet, SpecialtyViewSet, SessionViewSet

app_name = 'Doctor'

router = routers.DefaultRouter()
router.register('doctors', DoctorViewSet)
router.register('specialty', SpecialtyViewSet)
router.register('sessions', SessionViewSet)


urlpatterns = [
    path('', views.session_list, name='session_home'),
    path('sessions_details', views.sessions_details, name='sessions_details'),
    path('doctor_list', views.doctor_list, name='doctor_list'),
    path('create_session', views.create_session, name='create_session'),
    path('api/', include(router.urls), name='api_router'),
]

accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import signup_view

app_name = 'accounts'

urlpatterns = [
    path('accounts/signup/', signup_view, name='signup'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('accounts/password_reset/',auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/',auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]

djangohos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Doctor.urls', namespace='doctors')),
    path('', include('accounts.urls', namespace='accounts')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include('Doctor.urls', namespace='api_doctor')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Doctor/models.py
import datetime

from django.db import models

# Choices Sessions
CHOICES_SESSIONS = (
    ('Weekly Session', 'Weekly Session'),
    ('One Day Session', 'One Day Session'),
)
WEEKDAYS = (
  ("Monday", "Monday"),
  ("Tuesday", "Tuesday"),
  ("Wednesday", "Wednesday"),
  ("Thursday", "Thursday"),
  ("Friday", "Friday"),
  ("Saturday", "Saturday"),
  ("Sunday", "Sunday"),
)


# Data Doctor
class Doctor(models.Model):
    name = models.CharField(max_length=256)
    sessions = models.CharField(max_length=40, choices=CHOICES_SESSIONS)
    price = models.IntegerField(default=200)
    weekday = models.CharField(max_length=256,choices=WEEKDAYS,unique=True)
    from_hour = models.TimeField()
    to_hour = models.TimeField()

    class Meta:
        ordering = ('weekday', 'from_hour')
        unique_together = ('weekday', 'from_hour', 'to_hour')


    def __unicode__(self):
        return u'%s: %s - %s' % (self.get_weekday_display(),
                                 self.from_hour, self.to_hour)

    def __str__(self):
        return self.name


# Data Specialty
class Specialty(models.Model):
    name_sp = models.CharField(max_length=250, null=True, blank=True)
    sep = models.ForeignKey(Doctor, on_delete=models.CASCADE,null=True, blank=True)

    def __str__(self):
        return '%s ,Specialty: %s' % (self.sep, self.name_sp)


# Data Sessions
class Session(models.Model):
    name = models.CharField(max_length=50)
    title = models.ForeignKey(Specialty,on_delete=models.CASCADE)
    price = models.IntegerField()
    date = models.DateField(default=datetime.date.today)
    start_time = models.TimeField()
    end_time = models.TimeField()

    def __str__(self):
        return str(self.title)

Doctor/forms.py
from django.forms import ModelForm

from Doctor.models import Session


class UserSessionsForm(ModelForm):
    class Meta:
        model = Session
        fields = '__all__'

Doctor/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.models import User

# Create your views here.
from rest_framework.viewsets import ModelViewSet

from Doctor.forms import UserSessionsForm
from Doctor.models import Session, Doctor, Specialty


# page doctor list
from Doctor.serializer import DoctorSerializer, SpecialtySerializer, SessionSerializer





# function sessions list
def session_list(request):
    session_list = Session.objects.all()
    doctors = User.objects.all()
    return render(request, 'home.html', {'session_list': session_list, 'doctors': doctors})



# function sessions details
def sessions_details(request):
    sessions_details = Session.objects.all()
    return render(request,'sessions_details.html', {'sessions_details': sessions_details})


# function doctor list
def doctor_list(request):
    doctor_list = Doctor.objects.all()
    specialty = Specialty.objects.all()
    return render(request, 'doctor_list.html', {'doctor_list': doctor_list, 'specialty':specialty})



# create sessions book
def create_session(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = UserSessionsForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'Session Created Successfully')
                return redirect('/')

        else:
            form = UserSessionsForm()
        return render(request, 'create_session.html', {'form': form})
    else:
     return redirect('doctors:session_home')




# ViewSets define the view behavior

class DoctorViewSet(ModelViewSet):
    queryset = Doctor.objects.all()
    serializer_class = DoctorSerializer


class SpecialtyViewSet(ModelViewSet):
    queryset = Specialty.objects.all()
    serializer_class = SpecialtySerializer



class SessionViewSet(ModelViewSet):
    queryset = Session.objects.all()
    serializer_class = SessionSerializer

Doctor/templates/api.html
hello
<!--{% load rest_framework %}-->

<!--{% block content %}-->

<!--<form action="{% url 'doctors:doctor_view'  %}" method="POST">-->
<!--    {% csrf_token %}-->
<!--    {% render_form serializer %}-->
<!--    <input type="submit" value="Save">-->
<!--</form>-->

<!--{% endblock content %}-->

Doctor/templates/create_session.html
{% block body  %}

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
     <button type="submit">Save Session</button>
  </form>

</div>
{% endblock body %}

Doctor/templates/doctor_list.html
{% block body %}


{% for sepec in specialty %}
  Doctor:  {{ sepec.sep }}<br>
  Specialty: {{ sepec.name_sp }}<br><br/><br/>
{% endfor %}


{% for doctor in doctor_list %}
  Doctor: {{ doctor.name }} <br>
  Specialty: {{ doctor.Specialty.name_sp }}<br>
  Session: {{ doctor.sessions }}<br>
  Price:  {{ doctor.price }}<br>
  Weekday:  {{ doctor.weekday }}<br>
  From Hour:  {{ doctor.from_hour }}<br>
  To Hour:  {{ doctor.to_hour }}<br><hr/>
{% endfor %}

{% endblock %}

Doctor/templates/home.html
{% load static %}
{% block body %}

    {% if request.user.is_authenticated %}
     Hi, {{ request.user.username }}<br/>
      <a href="{% url 'accounts:logout' %}"> Logout</a>

    {% else %}
      <a href="{% url 'accounts:login' %}">Login</a>
      <a href="{% url 'accounts:signup' %}">Register</a>
    {% endif %}
<br><hr/>

<a href="http://127.0.0.1:8000/api/doctors/"> Doctors API</a><br/><br/>
<a href="http://127.0.0.1:8000/api/specialty/"> Specialty API</a><br/><br/>
<a href="http://127.0.0.1:8000/api/sessions/"> Sessions API</a><br/><br/>

<a href="{% url 'doctors:sessions_details'  %}" ><h2>Sessions</h2></a><br>
<a href="{% url 'doctors:create_session'  %}" ><h2>Book Doctor Sessions</h2></a><br>

<hr/>
<h1><a href="{% url 'doctors:doctor_list'  %}"> Doctors</a></h1>

{% endblock body%}

Doctor/templates/session_list.html
{% load static %}
{% block body %}

    {% if request.user.is_authenticated %}
     Hi, {{ request.user.username }}<br/>
      <a href="{% url 'accounts:logout' %}"> Logout</a>

    {% else %}
      <a href="{% url 'accounts:login' %}">Login</a>
      <a href="{% url 'accounts:signup' %}">Register</a>
    {% endif %}
<br><hr/>

<a href="http://127.0.0.1:8000/api/doctors/"> Doctors API</a><br/><br/>
<a href="http://127.0.0.1:8000/api/specialty/"> Specialty API</a><br/><br/>
<a href="http://127.0.0.1:8000/api/sessions/"> Sessions API</a><br/><br/>

<a href="{% url 'doctors:sessions_details'  %}" ><h2>Sessions</h2></a><br>
<a href="{% url 'doctors:create_session'  %}" ><h2>Book Doctor Sessions</h2></a><br>

<hr/>
<h1><a href="{% url 'doctors:doctor_list'  %}"> Doctors</a></h1>

{% endblock body%}

Doctor/templates/sessions_details.html
{% load static %}
{% block body %}

<h2>Sessions </h2>
{% for sessions in sessions_details %}
    Session Number: {{ sessions.id }} <br><br/>
    Name: {{ sessions.name }} <br><br/>
<!--    Choose Doctor: {{ sessions.doctor }} <br><br/>-->
    Title: {{ sessions.title }} <br><br/>
    Price: {{ sessions.price }} EGP <br><br/>
    Data: {{ sessions.date| date:"Y-m-d" }} <br><br/>
    Start Time: {{ sessions.start_time }}<br><br/>
    End Time: {{ sessions.end_time }}
<hr>
{% endfor %}

{% endblock body %}